package subagents

import (
	"os"
	"path/filepath"
	"strings"

	"orquestador-auditor/internal/agents"
	"orquestador-auditor/internal/assets"
	"orquestador-auditor/internal/components/filemerge"
	"orquestador-auditor/internal/markers"
	"orquestador-auditor/internal/model"
)

func Inject(homeDir string, adapter agents.Adapter, profile model.AuditProfile, useMarkers bool) error {
	if !adapter.SupportsSubAgents() {
		return nil
	}
	dir := adapter.SubAgentsDir(homeDir)
	if dir == "" {
		return nil
	}
	patternRoot := adapter.EmbeddedSubAgentsDir()
	if patternRoot == "" {
		return nil
	}
	if err := os.MkdirAll(dir, 0o755); err != nil {
		return err
	}
	entries, err := assets.List(patternRoot + "/*.md")
	if err != nil {
		return err
	}

	// Build a combined sub-agent content block for marker injection
	if useMarkers {
		return injectSubAgentsWithMarkers(dir, entries, profile)
	}

	keep := map[string]struct{}{}
	for _, entry := range entries {
		name := strings.TrimSuffix(filepath.Base(entry), filepath.Ext(entry))
		targetPath := filepath.Join(dir, filepath.Base(entry))
		if profile.IncludesComponent(model.ComponentSubAgents) && profile.AllowsSubAgent(name) {
			content, err := assets.Read(entry)
			if err != nil {
				return err
			}
			if err := filemerge.WriteIfChanged(targetPath, []byte(content)); err != nil {
				return err
			}
			keep[targetPath] = struct{}{}
		}
	}
	for _, entry := range entries {
		targetPath := filepath.Join(dir, filepath.Base(entry))
		if _, ok := keep[targetPath]; ok {
			continue
		}
		if err := os.Remove(targetPath); err != nil && !os.IsNotExist(err) {
			return err
		}
	}
	return nil
}

// injectSubAgentsWithMarkers creates a single combined file for all sub-agents
// wrapped in ORQUESTADOR markers, preventing drift on repeated syncs.
func injectSubAgentsWithMarkers(dir string, entries []string, profile model.AuditProfile) error {
	var content strings.Builder
	content.WriteString("# Security Specialist Sub-Agents\n")
	content.WriteString("<!-- Auto-generated by orquestador-auditor -- do not edit manually -->\n\n")

	for _, entry := range entries {
		name := strings.TrimSuffix(filepath.Base(entry), filepath.Ext(entry))
		if !profile.IncludesComponent(model.ComponentSubAgents) || !profile.AllowsSubAgent(name) {
			continue
		}
		assetContent, err := assets.Read(entry)
		if err != nil {
			return err
		}
		content.WriteString(markers.FormatMarkdownSection("subagent:"+name, "Sub-Agent: "+name, assetContent))
		content.WriteString("\n")
	}

	targetPath := filepath.Join(dir, "security-subagents.md")
	return filemerge.WriteIfChanged(targetPath, []byte(content.String()))
}
